services:
  
  # MongoDB container service
  mongoDB:
    image: mongo:latest
    restart: always
    volumes:
      - RecipeKeeperDB:/data/db
  
  # Unit Conversion Service
  unit-converter:
    image: "th3oth3rjak3/unit-converter"
    restart: always

  # RecipeKeeper application server
  app:
    build: .
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongoDB:27017
      DB_NAME: RecipeKeeperDB
      MICROSERVICE_URI: http://unit-converter:3002
    depends_on:
      - mongoDB
      - unit-converter
    restart: always

volumes:
  RecipeKeeperDB: {}