version: "1.0"
services:
  front-end:
    build: .
    ports:
      - "3000:3000"
  back-end:
    build: ./server
    ports:
      - "3001:3001"
  mongoDB:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - .:/database
  unit-converter:
    image: "th3oth3rjak3/unit-converter"
